#!/bin/bash
# 
# install script | MIT License
# 
# This script installs ProxDad to the user's home directory.
# 
# Copyright (C) 2024 Abhishek Singh
# 

source ./include/_utilspxd || exit 1

# Get sudo permission
sudo true

# Display default values and ask if the user wants to continue with them
echo "[Default values]"
echo "    ⤷ Proxy host: 172.31.102.29"
echo "    ⤷ Proxy port: 3128"
echo "    ⤷ Proxy username: edcguest"
echo "    ⤷ Proxy password: edcguest"

while true; do
    read -p "Do you want to continue with the default values? [Y/n]: " continue_choice

    if [[ -z "$continue_choice" ]] || [[ "${continue_choice,,}" == "y" || "${continue_choice,,}" == "yes" ]]; then
        proxy_host="172.31.102.29"
        proxy_port="3128"
        proxy_username="edcguest"
        proxy_password="edcguest"
        break
    elif [[ "${continue_choice,,}" == "n" || "${continue_choice,,}" == "no" ]]; then
        echo "[Custom values]"
        read -p "    ⤷ Enter proxy host: " proxy_host
        read -p "    ⤷ Enter proxy port: " proxy_port
        read -p "    ⤷ Enter proxy username: " proxy_username
        read -p "    ⤷ Enter proxy password: " -s proxy_password  # -s flag hides the password input
        echo ""
        break
    else
        echo "Invalid choice."
    fi
done

# Install ncat for ssh
if ! command -v ncat > /dev/null; then
    echo "Installing ncat for ssh proxy configuration..."
    sudo apt update -y && sudo apt install -y ncat

    if [ $? -eq 0 ]; then
        echo "'ncat' has been installed successfully"
    else
        echo "'ncat' installation has failed"
        exit 1
    fi
fi

# Create ssh config file if not
if command -v ssh > /dev/null; then
    if [ ! -f ~/.ssh/config ]; then
        mkdir -p ~/.ssh
        touch ~/.ssh/config
    fi
fi

# Create ProxDad folder
mkdir -p "$proxdad_installation_path"

# Copy scripts to the ProxDad folder
cp -r "./scripts" "$proxdad_installation_path"

# Give executable permissions to the scripts
chmod +x -R "$proxdad_installation_path/scripts"

# Copy includes to the ProxDad folder
cp -r "./include/"* "$proxdad_installation_path/scripts"

# Copy license to the ProxDad folder
cp "./LICENSE" "$proxdad_installation_path"

# Add ProxDad directory to the PATH variable
if ! grep -q "ProxDad scripts folder to PATH" "$HOME/.bashrc"; then
    echo "# Adding ProxDad scripts folder to PATH" >> "$HOME/.bashrc"
    echo "export PATH=\$PATH:$proxdad_installation_path/scripts" >> "$HOME/.bashrc"
    echo "# End of ProxDad scripts folder to PATH" >> "$HOME/.bashrc"
fi

# Store proxy configuration in the config file
echo "proxy_host=$proxy_host" > "$proxdad_config_file"
echo "proxy_port=$proxy_port" >> "$proxdad_config_file"
echo "proxy_username=$proxy_username" >> "$proxdad_config_file"
echo "proxy_password=$proxy_password" >> "$proxdad_config_file"

# Source the .bashrc file to apply changes to the current session
source "$HOME/.bashrc"

# Display success message
echo "ProxDad has been successfully installed at $proxdad_installation_path"

exit 0
