#!/bin/bash
#
# install script | MIT License
#
# This script installs ProxDad to user's home directory.
#
# Copyright (C) 2024 Abhishek Singh
#

_utilspxd_path="./include/_utilspxd"

source $_utilspxd_path || exit 1

# Check if ProxDad is already installed
if [ -d "$proxdad_installation_path" ]; then
    echo "ProxDad is already installed"
    exit 1
fi

# Get sudo permission for nothing
sudo true

# Create the destination folder
mkdir -p "$proxdad_installation_path"

# Copy the scripts to the destination folder
cp -r "./scripts" "$proxdad_installation_path"

# Give executable permissions to the scripts
chmod +x -R "$proxdad_installation_path/scripts"

# Copy the include folder to the destination folder
cp -r "./include/"* "$proxdad_installation_path/scripts"

# Add ProxDad directory to the PATH variable
echo "# Adding ProxDad scripts folder to PATH" >> "$HOME/.bashrc"
echo "export PATH=\$PATH:$proxdad_installation_path/scripts" >> "$HOME/.bashrc"
echo "# End of ProxDad scripts folder to PATH" >> "$HOME/.bashrc"

# Display default values and ask if the user wants to continue with them
echo "Default values"
echo "Proxy Host: 172.31.102.29"
echo "Proxy Port: 3128"
echo "Proxy Username: edcguest"
echo "Proxy Password: edcguest"
read -p "Do you want to continue with the default values? [Y/n]: " continue_choice

# Set default values if the user presses Enter without typing anything
if [ -z "$continue_choice" ] || [ "$continue_choice" == "y" ] || [ "$continue_choice" == "yes" ]; then
    proxy_host="172.31.102.29"
    proxy_port="3128"
    proxy_username="edcguest"
    proxy_password="edcguest"
else
    echo -e "\n"
    read -p "Enter proxy host: " proxy_host
    read -p "Enter proxy port: " proxy_port
    read -p "Enter proxy username: " proxy_username
    read -p "Enter proxy password: " -s proxy_password  # -s flag hides the password input
    echo -e "\n"
fi

# Store proxy configuration in the config file
echo "proxy_host=$proxy_host" > "$proxdad_config_file"
echo "proxy_port=$proxy_port" >> "$proxdad_config_file"
echo "proxy_username=$proxy_username" >> "$proxdad_config_file"
echo "proxy_password=$proxy_password" >> "$proxdad_config_file"

if ! command -v ncat &> /dev/null; then
    echo "Installing ncat for ssh proxy configuration..."
    sudo apt update -y && sudo apt install -y ncat

    if [ $? -eq 0 ]; then
        echo "'ncat' is installed successfully"
    else
        echo "ProxDad failed to install 'ncat'"
        echo "ProxDad uses 'ncat' to configure proxy settings to ssh"
        echo "ssh will not work with proxy settings, if 'ncat' is not installed"
        echo "Use 'sudo apt install ncat' to install it"
        exit 1
    fi
fi

# Display success message
echo "ProxDad has been succesfully installed at $proxdad_installation_path"

exit 0
