#!/bin/bash
# 
# uninstall script | MIT License
# 
# This script uninstalls ProxDad from user's home directory. 
# 
# Copyright (C) 2024 Abhishek Singh
# 

_utilspxd_path="./include/_utilspxd"

source $_utilspxd_path || exit 1

# Check if ProxDad is already uninstalled
if [ ! -d "$proxdad_installation_path" ]; then
    echo "ProxDad is already uninstalled"
    exit 1
fi

if is_proxdad_on; then
    echo -e "\e[1;32m\u25CF\e[0m ProxDad is \e[1;32mON\e[0m"
    echo "     Turn it off in order to uninstall it."
    echo "     Use 'offpxd' command to turn it off."
    exit 1
fi

# Prompt the user to confirm uninstallation
read -p "Do you really want to uninstall ProxDad? [y/N]: " uninstall_choice

if [ "${uninstall_choice,,}" != "y" ] && [ "${uninstall_choice,,}" != "yes" ]; then
    echo "Exiting without uninstalling."
    exit 1
fi

# Remove the destination folder and its contents
sudo rm -rf "$proxdad_installation_path"

# Remove ProxDad directory from PATH in .bashrc
sed -i "/# Adding ProxDad scripts folder to PATH/,/# End of ProxDad scripts folder to PATH/d" "$HOME/.bashrc"

# Source the .bashrc file to apply changes to the current session
source "$HOME/.bashrc"

# Display success message
echo "ProxDad has been succesfully uninstalled from $proxdad_installation_path"

exit 0
