#!/bin/bash
#
# uninstall script | MIT License
#
# This script uninstalls ProxDad version "v1.0" from a user's system. 
#
#
# It first checks if ProxDad is already uninstalled and if it's currently running.
# If not running, it prompts the user for confirmation to uninstall. 
# Upon confirmation, it removes the ProxDad installation directory /.proxdad and 
# its contents, then eliminates references to ProxDad in the user's .bashrc 
# file. Afterward, it informs the user of successful uninstallation and sources 
# the .bashrc file to apply changes.
#
#
# Copyright (C) 2024 Abhishek Singh
#

# Get the absolute path of the uninstall script
UNINSTALL_SCRIPT_PATH=$(dirname "$(realpath "${BASH_SOURCE[0]}")")

# Get the absolute path of the libproxdad script
libproxdad_path="$UNINSTALL_SCRIPT_PATH/lib/libproxdad"

if ! source $libproxdad_path; then
    exit 1
fi

# Check if ProxDad is already uninstalled
if [ ! -d "$proxdad_installation_path" ]; then
    echo "ProxDad is already uninstalled"
    exit 0
fi

if is_proxdad_on; then
    echo -e "\e[1;32m\u25CF\e[0m ProxDad is \e[1;32mON\e[0m"
    echo -e "Turn it off to uninstall it. Use 'offproxdad' command to turn it off"
    exit 0
fi

# Prompt the user to confirm uninstallation
read -p "Do you really want to uninstall ProxDad $proxdad_version? [y/N]: " uninstall_choice

if [ "${uninstall_choice,,}" != "y" ] && [ "${uninstall_choice,,}" != "yes" ]; then
    echo "Exiting without uninstalling."
    exit 0
fi

# Remove the destination folder and its contents
sudo rm -rf "$proxdad_installation_path"

# Remove ProxDad directory from PATH in .bashrc
sed -i "/# Adding ProxDad scripts folder to PATH/,/# End of ProxDad scripts folder to PATH/d" "$HOME/.bashrc"

echo "ProxDad has been succesfully uninstalled from $proxdad_installation_path"

# Source the .bashrc file to apply changes to the current session
source "$HOME/.bashrc"

exit 0
