#!/bin/bash

proxdad_version="v1.0"
proxdad_installation_path="$HOME/.proxdad"
proxdad_config_file="$proxdad_installation_path/proxdad.conf"

# Function to check if the user is root
is_user_root() {
    if [[ $EUID -eq 0 ]]; then
        return 0    # Yes, User is root
    else
        return 1    # No, User is not root
    fi
}

# Function to prevent root user from executing a script
prevent_root_execution() {
    if is_user_root; then
        echo -e "\e[1;31mDon't run this script as root user\e[0m"
        exit 1
    fi
}

# Function to check if proxy details is applied to environment
is_proxdad_on() {
    if grep -q "http_proxy" "/etc/environment"; then
        return 0  # Yes, ProxDad is ON
    else
        return 1  # No, ProxDad is OFF
    fi
}

get_proxdad_status() {
    if is_proxdad_on; then
        # Get proxy details from environment variables
        proxy_var=$(grep -E "http_proxy" "/etc/environment")

        # Extract host and port using awk
        proxy_host=$(echo "$proxy_var" | awk -F '[@:]' '{print $4}')
        proxy_port=$(echo "$proxy_var" | awk -F '[@:]' '{print $5}')

        echo "$proxy_host:$proxy_port"
    fi
}

prevent_root_execution
