#!/bin/bash
# 
# offpxd script | MIT License
# 
# This script turns OFF ProxDad version "v1.0" in a user's system.
# 
# Copyright (C) 2024 Abhishek Singh
# 

source _utilspxd || exit 1

if ! is_proxdad_on; then
    echo -e "\e[1;31m\u25CF\e[0m ProxDad is already OFF"
    exit 1
fi

# Remove proxy environment variables
sudo sed -i '/_proxy/d' /etc/environment

# Remove proxy for apt
if command -v git &> /dev/null; then
    sudo rm -f /etc/apt/apt.conf.d/40proxy
fi

# Remove proxy for gnome proxy applet
if command -v gsettings &> /dev/null; then
    gsettings reset org.gnome.system.proxy mode
    for protocol in "http" "https" "ftp"; do
        gsettings reset "org.gnome.system.proxy.$protocol" host
        gsettings reset "org.gnome.system.proxy.$protocol" port
    done
fi

# Remove proxy for Git
if command -v git &> /dev/null; then
    git config --global --unset http.proxy
    git config --global --unset https.proxy
fi

# Remove proxy for npm
if command -v npm &> /dev/null; then
    npm config delete proxy
    npm config delete https-proxy
fi

# Remove proxy for Snap
if command -v snap &> /dev/null; then
    sudo snap set system proxy.http=""
    sudo snap set system proxy.https=""
fi

# Remove proxy for ssh
if command -v ssh &> /dev/null; then
    sed -i '/^ *ProxyCommand /d' ~/.ssh/config
fi

# Display success message
echo -e "\e[1;31m\u25CF\e[0m ProxDad is turned OFF"

exit 0
