#!/bin/bash
# 
# offproxdad script | MIT License
# 
# This script turns OFF ProxDad version "v1.0" in a user's system.
# 
# 
# It first checks for root privileges to ensure it's not run with elevated 
# permissions. It then checks if ProxDad is already OFF.
# It removes environment variables, APT package manager settings, 
# GNOME proxy applet configurations, as well as proxy settings for Git, npm, 
# Snap, and SSH. Upon successful deconfiguration, it displays a message 
# confirming ProxDad is turned OFF.
# 
# 
# Copyright (C) 2024 Abhishek Singh
# 

libproxdad_path="./lib/libproxdad"

if [ -f "$libproxdad_path" ]; then
    source "$libproxdad_path"
else
    echo "Error: 'libproxdad' not found."
    exit 1
fi

prevent_root_execution

# Check ProxDad status
if ! is_proxdad_on; then
    echo "ProxDad is already OFF"
    exit 0
fi

# Remove proxy environment variables
sudo sed -i '/http_proxy/d' /etc/environment
sudo sed -i '/https_proxy/d' /etc/environment
sudo sed -i '/ftp_proxy/d' /etc/environment
sudo sed -i '/no_proxy/d' /etc/environment

# Remove proxy for apt
sudo rm -f /etc/apt/apt.conf.d/40proxy

# Remove proxy for gnome proxy applet
gsettings reset org.gnome.system.proxy mode
for protocol in "http" "https" "ftp"; do
    gsettings reset "org.gnome.system.proxy.$protocol" host
    gsettings reset "org.gnome.system.proxy.$protocol" port
done

# Remove proxy for Git
if command -v git &> /dev/null; then
    git config --global --unset http.proxy
    git config --global --unset https.proxy
fi

# Remove proxy for npm
if command -v npm &> /dev/null; then
    npm config delete proxy
    npm config delete https-proxy
fi

# Remove proxy for Snap
if command -v snap &> /dev/null; then
    sudo snap set system proxy.http=""
    sudo snap set system proxy.https=""
fi

# Remove proxy for ssh
sed -i '/^ *ProxyCommand /d' ~/.ssh/config

# Display a message indicating success
echo "ProxDad is turned OFF"
