#!/bin/bash
# 
# offpxd script | MIT License
# 
# This script turns OFF ProxDad for the user.
# 
# Copyright (C) 2024 Abhishek Singh
# 

set -e  # Exit on any failure

. _utilspxd

# Run basic shell safety checks
verify_bash
verify_non_root

if ! is_proxdad_on; then
    echo -e "${RED}${CIRCLE}${RESET} ProxDad is already OFF"
    exit 0
fi

# Remove proxy environment variables
sudo sed -i '/_proxy/d' /etc/environment

# Remove proxy for apt
if command -v git > /dev/null; then
    sudo rm -f /etc/apt/apt.conf.d/40proxy
fi

# Remove proxy for gnome proxy applet
if command -v gsettings > /dev/null; then
    gsettings reset org.gnome.system.proxy mode
    for protocol in "http" "https" "ftp"; do
        gsettings reset "org.gnome.system.proxy.$protocol" host
        gsettings reset "org.gnome.system.proxy.$protocol" port
    done
fi

# Remove proxy for KDE proxy applet
if command -v kwriteconfig5 > /dev/null; then
    kwriteconfig5 --file kioslaverc --group 'Proxy Settings' --key ProxyType 0
fi

# Remove proxy for Git
if command -v git > /dev/null; then
    git config --global --unset http.proxy
    git config --global --unset https.proxy
fi

# Remove proxy for npm
if command -v npm > /dev/null; then
    npm config delete proxy
    npm config delete https-proxy
fi

# Remove proxy for Snap
if command -v snap > /dev/null; then
    sudo snap set system proxy.http=""
    sudo snap set system proxy.https=""
fi

# Remove proxy for ssh
if command -v ssh > /dev/null; then
    sed -i '/^ *ProxyCommand /d' ~/.ssh/config
fi

# Display success message
echo -e "${RED}${CIRCLE}${RESET} ProxDad is turned OFF"

exit 0
