#!/bin/bash
# 
# onpxd script | MIT License
# 
# This script turns ON ProxDad for the user.
# 
# Copyright (C) 2024 Abhishek Singh
# 

source _utilspxd || exit 1

if is_proxdad_on; then
    echo -e "\e[1;32m\u25CF\e[0m ProxDad is already ON"
    exit 0
fi

source $proxdad_config_file || exit 1

# Backup of environment
sudo cp /etc/environment /etc/environment.bak

# Set proxy environment variables for system-wide use
sudo tee -a /etc/environment > /dev/null << EOF
http_proxy="http://${proxy_username}:${proxy_password}@${proxy_host}:${proxy_port}"
https_proxy="http://${proxy_username}:${proxy_password}@${proxy_host}:${proxy_port}"
ftp_proxy="http://${proxy_username}:${proxy_password}@${proxy_host}:${proxy_port}"
no_proxy="localhost,127.0.0.1"
EOF

# Set proxy for apt (package manager)
if command -v apt > /dev/null; then
sudo tee -a /etc/apt/apt.conf.d/40proxy > /dev/null << EOF
Acquire::http::proxy "http://${proxy_username}:${proxy_password}@${proxy_host}:${proxy_port}";
Acquire::https::proxy "http://${proxy_username}:${proxy_password}@${proxy_host}:${proxy_port}";
Acquire::ftp::proxy "http://${proxy_username}:${proxy_password}@${proxy_host}:${proxy_port}";
EOF
fi

# Set proxy for gnome applet, kde applet, git, npm and snap
source _cmmnpxd || exit 1
set_proxies

# Set proxy for ssh
if command -v ssh > /dev/null; then
    echo -e "ProxyCommand ncat --proxy-type http --proxy $proxy_host:$proxy_port --proxy-auth $proxy_username:$proxy_password %h %p" >> ~/.ssh/config
fi

# Display success message
echo -e "\e[1;32m\u25CF\e[0m ProxDad is turned ON"

exit 0
