#!/bin/bash
# 
# onpxd script | MIT License
# 
# This script turns ON ProxDad version "v1.0" in a user's system.
# 
# 
# It first checks for root privileges to ensure it's not run with elevated 
# permissions. It then checks if ProxDad is already ON and if the 
# configuration file exists before configuring the proxy settings system-wide. 
# It modifies environment variables, APT package manager settings, 
# GNOME proxy applet configurations, as well as proxy settings for Git, npm, 
# Snap, and SSH. Upon successful configuration, it displays a message 
# confirming ProxDad is turned ON.
# 
# 
# Copyright (C) 2024 Abhishek Singh
# 

source _utilspxd || exit 1

# Check ProxDad status
if is_proxdad_on; then
    echo -e "\e[1;32m\u25CF\e[0m ProxDad is already \e[1;32mON\e[0m"
    exit 0
fi

source $proxdad_config_file || exit 1

# Backup of environment
sudo cp /etc/environment /etc/environment.bak

# Set proxy environment variables for system-wide use
sudo cat >> /etc/environment << EOF
export http_proxy=http://${proxy_username}:${proxy_password}@${proxy_host}:${proxy_port}
export https_proxy=http://${proxy_username}:${proxy_password}@${proxy_host}:${proxy_port}
export http_proxy=http://${proxy_username}:${proxy_password}@${proxy_host}:${proxy_port}
export no_proxy=localhost,127.0.0.1
EOF

# Set proxy for apt (package manager)
if command -v apt &> /dev/null; then
    sudo cat >> /etc/apt/apt.conf.d/40proxy << EOF
Acquire::http::proxy "http://${proxy_username}:${proxy_password}@${proxy_host}:${proxy_port}";
Acquire::https::proxy "http://${proxy_username}:${proxy_password}@${proxy_host}:${proxy_port}";
Acquire::ftp::proxy "http://${proxy_username}:${proxy_password}@${proxy_host}:${proxy_port}";
EOF
fi

# Set proxy for gnome proxy applet
if command -v gsettings &> /dev/null; then
    gsettings set org.gnome.system.proxy mode 'manual'
    for protocol in "http" "https" "ftp"; do
        gsettings set "org.gnome.system.proxy.$protocol" host "$proxy_username:$proxy_password@$proxy_host"
        gsettings set "org.gnome.system.proxy.$protocol" port $proxy_port
    done
fi

# Set proxy for Git
if command -v git &> /dev/null; then
    git config --global http.proxy "http://${proxy_username}:${proxy_password}@${proxy_host}:${proxy_port}"
    git config --global https.proxy "http://${proxy_username}:${proxy_password}@${proxy_host}:${proxy_port}"
fi

# Set proxy for npm
if command -v npm &> /dev/null; then
    npm config set proxy "http://${proxy_username}:${proxy_password}@${proxy_host}:${proxy_port}"
    npm config set https-proxy "http://${proxy_username}:${proxy_password}@${proxy_host}:${proxy_port}"
fi

# Set proxy for Snap
if command -v snap &> /dev/null; then
    sudo snap set system proxy.http="http://${proxy_username}:${proxy_password}@${proxy_host}:${proxy_port}"
    sudo snap set system proxy.https="http://${proxy_username}:${proxy_password}@${proxy_host}:${proxy_port}"
fi

# Set proxy for ssh
if command -v ssh &> /dev/null; then
    echo -e "ProxyCommand ncat --proxy-type http --proxy $proxy_host:$proxy_port --proxy-auth $proxy_username:$proxy_password %h %p" >> ~/.ssh/config
fi

# Display a message indicating success
echo -e "\e[1;32m\u25CF\e[0m ProxDad is turned \e[1;32mON\e[0m"

exit 0
