#!/bin/bash
# 
# proxdad | MIT License
# 
# This script introduces ProxDad to the user. 
# 
# Copyright (C) 2024 Abhishek Singh
# 

set -e  # Exit on any failure

. _utilspxd

# Run basic shell safety checks
verify_bash
verify_non_root

# Function to display usage information
usage() {
    cat << EOF
Usage: $(basename "$0") [-h | --help] [command]

Options:
  -h, --help                  Display this help

Commands:
  on                          Turn on ProxDad
  off                         Turn off ProxDad
  restart                     Restart ProxDad
  status                      Get status of ProxDad
  uninstall                   Uninstall ProxDad
  set                         Set ProxDad settings
    -i <host>                 Set proxy host
    -p <port>                 Set proxy port
    -u <username>             Set proxy username
    -w <password>             Set proxy password

Examples:
  proxdad on
  proxdad off

ProxDad is installed at $proxdad_installation_path
ProxDad settings are specified in $proxdad_config_file

For bug reports, please visit: 
https://github.com/abhisheksinghforsure/proxdad/issues

This is free software; see the license for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
EOF
    exit 0
}

# Parse command-line options
[[ $# -eq 0 ]] && { usage; }

case $1 in
    -h|--help) usage ;;
    on) onpxd ;;
    off) offpxd ;;
    restart) restartpxd ;;
    status) statuspxd ;;
    uninstall) uninstallpxd ;;
    set) shift; setpxd "$@" ;;
    *) 
        echo "Error: Invalid command specified."; 
        exit 1 
        ;;
esac
