#!/bin/bash
#
# proxdad | MIT License
#
# This script introduces ProxDad to a user. 
#
# Copyright (C) 2024 Abhishek Singh
#

source _utilspxd || exit 1

# Define usage and version information
usage() {
    cat << EOF
Usage: $(basename "$0") [-h | --help] [-v | --version] [command]

Options:
  -h, --help            Display this help
  -v, --version         Display version information

Commands:
  on                    Turn on ProxDad
  off                   Turn off ProxDad
  restart               Restart ProxDad
  status                Get status of ProxDad
  set                   Set ProxDad settings
    -i <host>           Set proxy host
    -p <port>           Set proxy port
    -u <username>       Set proxy username
    -w <password>       Set proxy password

ProxDad $proxdad_version is installed at $proxdad_installation_path
ProxDad settings are specified in $proxdad_config_file

For bug reports, please visit: 
https://github.com/abhisheksinghforsure/proxdad/issues

This is free software; see the license for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
EOF
    exit 0
}

version() {
    echo "$(basename "$0") $proxdad_version"
    exit 0
}

# Parse command-line options
[[ $# -eq 0 ]] && { usage; }

case $1 in
    -h|--help) usage ;;
    -v|--version) version ;;
    on) onpxd ;;
    off) offpxd ;;
    restart) restartpxd ;;
    status) statuspxd ;;
    set) shift; setpxd "$@" ;;
    *) 
        echo "Error: Invalid command specified."; 
        exit 1 
        ;;
esac
