#!/bin/bash

source _utilspxd || exit 1

if ! is_proxdad_on; then
    echo -e "\e[1;31m\u25CF\e[0m ProxDad is \e[1;31mOFF\e[0m"
    exit 1
fi

source $proxdad_config_file || exit 1
source _cmmnpxd || exit 1

sudo sed -i "/^export \(http\|https\|ftp\)_proxy=/s|=.*|=\"http://${proxy_username}:${proxy_password}@${proxy_host}:${proxy_port}\"|" /etc/environment

if command -v apt &> /dev/null; then
    sudo sh -c "echo 'Acquire::http::proxy \"http://${proxy_username}:${proxy_password}@${proxy_host}:${proxy_port}\";\nAcquire::https::proxy \"http://${proxy_username}:${proxy_password}@${proxy_host}:${proxy_port}\";\nAcquire::ftp::proxy \"http://${proxy_username}:${proxy_password}@${proxy_host}:${proxy_port}\";' > /etc/apt/apt.conf.d/40proxy"
fi

set_proxies

sed -i "s/^ *ProxyCommand.*/ProxyCommand ncat --proxy-type http --proxy $proxy_host:$proxy_port --proxy-auth $proxy_username:$proxy_password %h %p/" ~/.ssh/config

echo -e "ProxDad is restarted"

exit 0
