#!/bin/bash

source _utilspxd || exit 1

if ! is_proxdad_on; then
    echo -e "\e[1;31m\u25CF\e[0m ProxDad is \e[1;31mOFF\e[0m"
    exit 1
fi

source $proxdad_config_file || exit 1
source _cmmnpxd || exit 1

set_proxies

sudo sed -i '/_proxy/d' /etc/environment
sudo tee -a /etc/environment > /dev/null << EOF
export http_proxy=http://${proxy_username}:${proxy_password}@${proxy_host}:${proxy_port}
export https_proxy=http://${proxy_username}:${proxy_password}@${proxy_host}:${proxy_port}
export ftp_proxy=http://${proxy_username}:${proxy_password}@${proxy_host}:${proxy_port}
export no_proxy=localhost,127.0.0.1
EOF

if command -v apt &> /dev/null; then
    sudo rm -f /etc/apt/apt.conf.d/40proxy
    sudo tee -a /etc/apt/apt.conf.d/40proxy > /dev/null << EOF
Acquire::http::proxy "http://${proxy_username}:${proxy_password}@${proxy_host}:${proxy_port}";
Acquire::https::proxy "http://${proxy_username}:${proxy_password}@${proxy_host}:${proxy_port}";
Acquire::ftp::proxy "http://${proxy_username}:${proxy_password}@${proxy_host}:${proxy_port}";
EOF
fi

if command -v ssh &> /dev/null; then
    sed -i '/^ *ProxyCommand /d' ~/.ssh/config
    echo -e "ProxyCommand ncat --proxy-type http --proxy $proxy_host:$proxy_port --proxy-auth $proxy_username:$proxy_password %h %p" >> ~/.ssh/config
fi

echo -e "ProxDad is restarted"

exit 0
