#!/bin/bash
#
# setpxd | MIT License
#
# This script sets ProxDad configurations.
#
# Copyright (C) 2024 Abhishek Singh
#

source _utilspxd || exit 1

# Function to display usage information
usage() {
    cat << EOF
Usage: $(basename "$0") [options]

Options:
  -h, --help            Display this help

  -i <host>             Set proxy host
  -p <port>             Set proxy port
  -u <username>         Set proxy username
  -w <password>         Set proxy password

Examples:
  $(basename "$0") -i 172.31.102.29 -p 3128
  $(basename "$0") -i 172.31.102.29 -p 3128 -u edcguest -w edcguest

ProxDad settings are specified in $proxdad_config_file
EOF
    exit 0
}

# Function to update config file
update_proxdad_config_file() {
    source $proxdad_config_file || exit 1

    # Update config based on arguments
    [[ $# -eq 0 ]] && { usage; }

    while [[ $# -gt 0 ]]; do
        case "$1" in
            -h|--help) usage ;;
            -i)
                sed -i "s/^proxy_host=.*/proxy_host=$2/" "$proxdad_config_file"
                shift 2
                ;;
            -p)
                sed -i "s/^proxy_port=.*/proxy_port=$2/" "$proxdad_config_file"
                shift 2
                ;;
            -u)
                sed -i "s/^proxy_username=.*/proxy_username=$2/" "$proxdad_config_file"
                shift 2
                ;;
            -w)
                sed -i "s/^proxy_password=.*/proxy_password=$2/" "$proxdad_config_file"
                shift 2
                ;;
            *)
                echo "Error: Invalid option specified."
                exit 1
                ;;
        esac
    done

    exit 0
}

# Parse command-line options
update_proxdad_config_file "$@"
