#!/bin/bash
# 
# statusproxdad script | MIT License
# 
# This script checks whether proxy details are applied to the system environment.
# 
#
# It defines two functions: is_proxdad_on, which examines if the proxy details 
# are present in the /etc/environment file, and get_proxdad_status, which 
# retrieves and formats the proxy host and port if the proxy is enabled. 
# The script also verifies if it's executed directly and if so, it calls 
# get_proxdad_status to obtain and display the proxy details along with 
# indicating whether "ProxDad" (proxy) is on or off. It essentially serves as 
# a tool to check and report the status of a proxy configuration on the system.
# 
# 
# Copyright (C) 2024 Abhishek Singh
# 

libproxdad_path="./lib/libproxdad"

if [ -f "$libproxdad_path" ]; then
    source "$libproxdad_path"
else
    echo "Error: 'libproxdad' not found."
    exit 1
fi

prevent_root_execution

proxdad_status=$(get_proxdad_status)

if [ -n "$proxdad_status" ]; then
    echo "$proxdad_status"
    echo "ProxDad is ON"
else
    echo "ProxDad is OFF"
fi
