#!/bin/bash
# 
# statuspxd script | MIT License
# 
# This script checks the status of ProxDad for the user.
# 
# Copyright (C) 2024 Abhishek Singh
# 

set -e  # Exit on any failure

source _utilspxd

# Check if a proxy is configured
if proxy_var=$(grep -E "http_proxy" "/etc/environment"); then

    # Clean up proxy details
    proxy_var=${proxy_var#*://}
    proxy_var=${proxy_var//\"/}
    
    # Extract credentials, host, and port using IFS
    IFS=':@/' read -r proxy_username proxy_password proxy_host proxy_port <<< "${proxy_var}"

    # Display proxy status
    echo -e "${GREEN}${CIRCLE}${RESET} ProxDad is ON"

    # Verify proxy server connectivity
    if timeout 1 bash -c ">/dev/tcp/$proxy_host/$proxy_port" 2>/dev/null; then
        echo -e "    ├── Proxy Server    : ${GREEN}[▲] Up${RESET}"

        # Verify internet connectivity through proxy
        if curl -s --proxy "$proxy_var" --max-time 2 --fail -o /dev/null "http://clients3.google.com/generate_204"; then
            echo -e "    └── Internet Access : ${GREEN}[✔] Yes${RESET}"
        else
            echo -e "    └── Internet Access : ${RED}[✘] No${RESET}"
        fi
    else
        echo -e "    └── Proxy Server    : ${RED}[▼] Down${RESET}"
    fi

    # Display proxy configuration
    echo -e "  Proxy Configuration\n\
    ├── Host            : $proxy_host\n\
    ├── Port            : $proxy_port\n\
    ├── Username        : $proxy_username\n\
    └── Password        : ${proxy_password//?/*}"

else
    echo -e "${RED}${CIRCLE}${RESET} ProxDad is OFF"
fi

exit 0
