#!/bin/bash
# 
# statuspxd script | MIT License
# 
# This script checks whether proxy details are applied to the system environment.
# 
# Copyright (C) 2024 Abhishek Singh
# 

if proxy_var=$(grep -E "http_proxy" "/etc/environment"); then
    proxy_host=$(awk -F '[@:]' '{print $4}' <<< "$proxy_var")
    proxy_port=$(awk -F '[@:]' '{print $5}' <<< "$proxy_var")
    
    echo -e "\e[1;32m\u25CF\e[0m ProxDad is \e[1;32mON\e[0m"
    echo "     Proxy host: $proxy_host"
    echo "     Proxy port: $proxy_port"
else
    echo -e "\e[1;31m\u25CF\e[0m ProxDad is \e[1;31mOFF\e[0m"
fi

exit 0
