#!/bin/bash
# 
# statuspxd script | MIT License
# 
# This script checks whether proxy details are applied to the system environment.
# 
#
# It defines two functions: is_proxdad_on, which examines if the proxy details 
# are present in the /etc/environment file, and get_proxdad_status, which 
# retrieves and formats the proxy host and port if the proxy is enabled. 
# The script also verifies if it's executed directly and if so, it calls 
# get_proxdad_status to obtain and display the proxy details along with 
# indicating whether "ProxDad" (proxy) is on or off. It essentially serves as 
# a tool to check and report the status of a proxy configuration on the system.
# 
# 
# Copyright (C) 2024 Abhishek Singh
# 

if ! source _utilspxd; then
    exit 1
fi

proxdad_status=$(get_proxdad_status)

if [ -n "$proxdad_status" ]; then
    echo -e "\e[1;32m\u25CF\e[0m ProxDad is \e[1;32mON\e[0m"
    echo "$proxdad_status"
else
    echo -e "\e[1;31m\u25CF\e[0m ProxDad is \e[1;31mOFF\e[0m"

fi

exit 0
