#!/bin/bash
# 
# uninstall script | MIT License
# 
# This script uninstalls ProxDad from user's home directory. 
# 
# Copyright (C) 2024 Abhishek Singh
# 

source _utilspxd || exit 1

# Prompt the user to confirm uninstallation
read -p "Do you really want to uninstall ProxDad? [y/N]: " uninstall_choice

if [ "${uninstall_choice,,}" != "y" ] && [ "${uninstall_choice,,}" != "yes" ]; then
    echo "Exiting without uninstalling."
    exit 1
fi

# Execute offpxd script to turn OFF ProxDad if ON
offpxd

# Remove the destination folder and its contents
sudo rm -rf "$proxdad_installation_path"

# Remove ProxDad directory from PATH in .bashrc
sed -i "/# Adding ProxDad scripts folder to PATH/,/# End of ProxDad scripts folder to PATH/d" "$HOME/.bashrc"

# Source the .bashrc file to apply changes to the current session
source "$HOME/.bashrc"

# Display success message
echo "ProxDad has been succesfully uninstalled from $proxdad_installation_path"

exit 0
