#!/bin/bash
# 
# uninstallpxd script | MIT License
# 
# This script uninstalls ProxDad from the user's home directory. 
# 
# Copyright (C) 2024 Abhishek Singh
# 

set -e  # Exit on any failure

. _utilspxd

# Run basic shell safety checks
verify_bash
verify_non_root

# Prompt the user to confirm uninstallation
read -p "Do you really want to uninstall ProxDad? [y/N]: " uninstall_choice

if [ "${uninstall_choice,,}" != "y" ] && [ "${uninstall_choice,,}" != "yes" ]; then
    echo "Abort."
    exit 1
fi

# Execute offpxd script to turn OFF ProxDad if ON
offpxd > /dev/null

# Remove the ProxDad folder and its contents
sudo rm -rf "$proxdad_installation_path"

# Remove ProxDad directory from PATH in .bashrc
sed -i "/# Adding ProxDad scripts folder to PATH/,/# End of ProxDad scripts folder to PATH/d" "$HOME/.bashrc"

# Display success message
echo "ProxDad has been successfully uninstalled from $proxdad_installation_path"

exit 0
