#!/bin/bash
# 
# whereproxdad script | MIT License
# 
# This script reveals ProxDad version "v1.0" installation path in a user's system.
# 
# 
# It is intended to provide users with a concise notification regarding 
# where ProxDad is installed on their system, ensuring clarity and ease 
# of access for future reference.
# 
# 
# Copyright (C) 2024 Abhishek Singh
# 

# Check if the script is run by root
if [ "$(id -u)" = "0" ]; then
    echo "DON'T run as root."
    exit 1
fi

proxdad_installation_path="$HOME/.proxdad"

echo "ProxDad is installed at $proxdad_installation_path"
