#!/bin/bash
# 
# _cmmnpxd include | MIT License
# 
# This include provides common functions for ProxDad functionality.
# 
# Copyright (C) 2024 Abhishek Singh
# 

set_proxies() {
    # Set proxy for gnome proxy applet
    if command -v gsettings &> /dev/null; then
        gsettings set org.gnome.system.proxy mode 'manual'
        for protocol in "http" "https" "ftp"; do
            gsettings set "org.gnome.system.proxy.$protocol" host "$proxy_username:$proxy_password@$proxy_host"
            gsettings set "org.gnome.system.proxy.$protocol" port $proxy_port
        done
    fi

    # Set proxy for Git
    if command -v git &> /dev/null; then
        git config --global http.proxy "http://${proxy_username}:${proxy_password}@${proxy_host}:${proxy_port}"
        git config --global https.proxy "http://${proxy_username}:${proxy_password}@${proxy_host}:${proxy_port}"
    fi

    # Set proxy for npm
    if command -v npm &> /dev/null; then
        npm config set proxy "http://${proxy_username}:${proxy_password}@${proxy_host}:${proxy_port}"
        npm config set https-proxy "http://${proxy_username}:${proxy_password}@${proxy_host}:${proxy_port}"
    fi

    # Set proxy for Snap
    if command -v snap &> /dev/null; then
        sudo snap set system proxy.http="http://${proxy_username}:${proxy_password}@${proxy_host}:${proxy_port}"
        sudo snap set system proxy.https="http://${proxy_username}:${proxy_password}@${proxy_host}:${proxy_port}"
    fi
}
