#!/bin/bash

proxdad_version="v1.0"
proxdad_installation_path="$HOME/.proxdad"
proxdad_config_file="$proxdad_installation_path/proxdad.conf"

# Function to prevent root user from executing a script
prevent_root_execution() {
    if [[ $EUID -eq 0 ]]; then
        echo -e "\e[1;31mDon't run this script as root user\e[0m"
        exit 1
    fi
}

# Function to check if proxy details is applied to environment
is_proxdad_on() {
    if grep -q "http_proxy" "/etc/environment"; then
        return 0  # Yes, ProxDad is ON
    else
        return 1  # No, ProxDad is OFF
    fi
}

# Function to get ProxDad proxy status
get_proxdad_status() {
    # Check if http_proxy is set in /etc/environment and retrieve proxy details
    if proxy_var=$(grep -E "http_proxy" "/etc/environment"); then
        # Extract host and port using awk
        proxy_host=$(awk -F '[@:]' '{print $4}' <<< "$proxy_var")
        proxy_port=$(awk -F '[@:]' '{print $5}' <<< "$proxy_var")

        echo "$proxy_host:$proxy_port"
    fi
}

prevent_root_execution
